(from <- as.Date("2000-01-31"))
(seq(from, by = "month", length = 4))
(a <- mondate(from))
(b <- as.numeric(a))
(c <- b - .02)
(d <- mondate(c))
(e <- seq(d, length = 4))
(f <- as.Date(e))

(c2 <- b)
(d2 <- mondate(c2))
(e2 <- seq(d2, length = 4))
(f2 <- as.Date(e2))

(from <- as.Date("2000-01-01"))
(seq(from, by = "month", length = 4))
(a <- mondate(from))
(b <- as.numeric(a))

(c2 <- b)
(d2 <- mondate(c2))
(e2 <- seq(d2, length = 4))
(f2 <- as.Date(e2))
