setGeneric("seqmondate", function(from, to, ...) standardGeneric("seqmondate"))
setMethod("seqmondate", "mondate", function(from, to, ...) seq.mondate(from, to, ...))
setMethod("seqmondate", c("missing", "mondate"), function(to, ...) seq.mondate(from, to, ...))
setMethod("seqmondate", c("Date", "Date"), function(from, to, ...)
  as.Date(seq(mondate(as.numeric(mondate(from)) - .02), 
              mondate(as.numeric(mondate(to  )) - .02),
              ...)
          )
  )
setMethod("seqmondate", c("Date", "missing"), function(from, to, ...)
  as.Date(seq(mondate(as.numeric(mondate(from)) - .02), ...))
  )
setMethod("seqmondate", c("missing", "Date"), function(from, to, ...)
  stop("'from' cannot be missing in call to \"seqmondate\"")
)

setMethod("seqmondate", "POSIXlt", function(from, to, ...) 
  structure(as.POSIXlt(seqmondate(as.Date(from), as.Date(to), ...)), tzone = attr(from, "tzone"))
  )
setMethod("seqmondate", c("POSIXlt", "missing"), function(from, to, ...) 
  structure(as.POSIXlt(seqmondate(as.Date(from), ...), tzone = attr(from, "tzone")))
)
setMethod("seqmondate", c("missing", "POSIXlt"), function(from, to, ...)
  stop("'from' cannot be missing in call to \"seqmondate\"")
)

setMethod("seqmondate", "POSIXct", function(from, to, ...) 
  as.POSIXct(seqmondate(as.POSIXlt(from), as.POSIXlt(to), ...))
  )
setMethod("seqmondate", c("POSIXct", "missing"), function(from, to, ...) 
  as.POSIXct(seqmondate(as.POSIXlt(from), ...))
)
setMethod("seqmondate", c("missing", "POSIXct"), function(from, to, ...)
  stop("'from' cannot be missing in call to \"seqmondate\"")
)

